# Generated by Django 4.2.16 on 2026-02-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='internships',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='work_history',
        ),
    ]
